[package]
name = "problems_0601_0700"
version = "0.1.0"
authors = ["pavel.varyukhichev <dae.fromru@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
